#! /bin/bash

# Correct formatting of the CSV

source logins

sed -ri -e '1d' -e '2d' -e 's/[\ |\t]+\"/;/' -e 's/"[\ |\t]+"/;/g' -e 's/"$//' -e 's/[\ |\t]+/_/g' $CSV

# removing accents and non standard characters
iconv -f latin1 -t ASCII//TRANSLIT -o $CSV $CSV
